[[constraint]]
  name = "github.com/Microsoft/ApplicationInsights-Go"
  version = "0.4.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[prune]
  go-tests = true
  unused-packages = true
